# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\git_source\smart_switch_pc\testbench.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import serial.tools.list_ports
import time
import sys
reload(sys)
sys.setdefaultencoding('utf8')
import serial.tools.list_ports
from logger import LOGGER_ERROR, LOGGER_INFO, LOGGER_DEBUG
import winsound


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class SerialError(Exception):
    pass

class MyThread(QtCore.QThread):
    sinOut = QtCore.pyqtSignal(str)
    msgOut = QtCore.pyqtSignal(str)
    errorOut = QtCore.pyqtSignal(str)
    beepOut = QtCore.pyqtSignal(str)
    sinOutRF = QtCore.pyqtSignal(str)

    def __init__(self, parent=None):
        super(MyThread,self).__init__(parent)
        self.testbed_reset = 'ft_reset_s\r'
        self.dev_on_cmd = 'set_output_on\r\n'
        self.dev_off_cmd = 'set_output_off\r\n'
        self.testbed_on_cmd = 'ft_read_on\r'
        self.testbed_off_cmd = 'ft_read_on\r'       
        self.onResult_base = '01010101010101010101010'
        self.offResult_base = '10101010101010101010101'
        #self.switch_check_pos = [0,1,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20,21,22]
        self.switch_check_pos = [0,1,5,6,7,8,9,10,11,12,13,14,16,17,19,20,21,22]
        #self.remoter_check_pos = [0,1,5,6,7,15,16,17,18,19]
        self.remoter_check_pos = [0,1,5,6,7,15,16,17,19]
        #self.sensor_check_pos = [2,3,4,5,6,7,16,17,18]
        self.sensor_check_pos = [0,2,3,6,7]
        self.rf_start = "start_rf_test\r\n"
        self.usr_key = "set_usr_key f119072b3e242c2cbe9618711f91a869\r\n"
        self.timeout = 30

    def setDevType(self, pDevType):
        self.device_type = str(pDevType)

    def setDevPort(self, pDevPort):
        self.device_port = str(pDevPort)

    def setDevRate(self, pDevRate):
        self.device_rate = int(pDevRate)

    def setTbPort(self, pTbPort):
        self.testbed_port = str(pTbPort)

    def setTbRate(self, pTbRate):
        self.testbed_rate = int(pTbRate)

    def run(self):
        try:
            print self.device_port
            LOGGER_INFO("#"*30 + "Connection Test" + "#"*30)
            self.msgOut.emit(u"<font color='green'>连通性测试开始....</font>")
            if not self._openSerialPort():
                raise SerialError                
            self.msgOut.emit(u"串口连接成功")
            
            LOGGER_INFO("***********Testboard Reset**************")
            self._boardReset()
            self.msgOut.emit(u"测试中转板复位成功")
            
            LOGGER_INFO("***********Connection Test Procedure Start**************")
            onResp = self._getOutput(self.dev_on_cmd, self.testbed_on_cmd)
            resultOn = self._resultCompare(self.device_type, onResp, self.onResult_base)
            self.msgOut.emit(u"连通性测试进行中....")
            print "result on", resultOn
            
            offResp = self._getOutput(self.dev_off_cmd, self.testbed_off_cmd)
            resultOff = self._resultCompare(self.device_type, offResp, self.offResult_base)
            self.msgOut.emit(u"连通性测试进行中....")
            print "result off", resultOff
            resultFinal = self.device_type + "," + ",".join(self._resultCompare("other", resultOn, resultOff))
            print resultFinal

            
            self.msgOut.emit(u"<font color='green'>连通性测试结束</font>")
            self.sinOut.emit(resultFinal)

            time.sleep(1)
            
            LOGGER_INFO("#"*30 + "RF Test Start" + "#"*30)
            self.msgOut.emit(u"<font color='green'>传输测试开始....</font>")


            if not self._sendUserKey(self.usr_key):
                raise Exception(u"User key 发送失败")
            self.msgOut.emit(u"user key发送成功")
            LOGGER_DEBUG("***********Send User Key Successfully**************")
            
            time.sleep(2)

            if not self._boardReset():
                raise Exception(u"测试中转板复位失败")
            self.msgOut.emit(u"测试中转板复位成功")
            LOGGER_DEBUG("***********Testboard Reset Successfully**************")
            
            time.sleep(2)
            if not self._startRfTest(self.rf_start):
                result = "FAILED"
                self.msgOut.emit(u"<font color='red'>传输测试失败</font>")
                LOGGER_DEBUG("***********RF start cmd excute failed**************")
            else:
                result = "PASSED"
                
                self.msgOut.emit(u"<font color='green'>传输测试成功</font>")
                LOGGER_DEBUG("***********RF start cmd excute successfully**************")
          
            if (result == "PASSED") and (not "FAILED" in resultFinal):
                winsound.Beep(2800,1500)
            self._closeSerialPort()
            self.msgOut.emit(u"<font color='green'>传输测试结束</font>")
            self.sinOutRF.emit(result)            

        except SerialError:            
            self.errorOut.emit(u"<font color='red'>串口连接失败，请重试。</font>")
        except Exception, e:
            self.errorOut.emit("<font color='red'>Exception: %s</font>"%e)
            self._closeSerialPort()
            

    def _openSerialPort(self):
        try:
            self.device_ser = serial.Serial(self.device_port, baudrate=self.device_rate)
        except:
             return False
        else:
            try:
                self.testbed_ser = serial.Serial(self.testbed_port, baudrate=self.testbed_rate)
                return True
            except:
                self.device_ser.close()
                return False

    def _boardReset(self): # boardReset failed, alert warning
        self.testbed_ser.write(self.testbed_reset)
        LOGGER_INFO("To testbed:    %s"%self.testbed_reset)
        time.sleep(2)
        strlength = self.testbed_ser.inWaiting()
        data = self.testbed_ser.read(strlength)
        if not "done" in data:
            raise Exception("No return from boardreset!")
        LOGGER_INFO("From testbed:     %s"%data)
        resp = self.device_ser.read(self.device_ser.inWaiting())
        LOGGER_INFO("From device:     %s"%resp)
        if not "In factory mode" in resp:
            raise Exception("Not enter in factory mode!")
        return True

    def _getOutput(self, pDev_cmd, pTb_cmd):
        
        #time.sleep(0.4)
        #pc <-> switch
        self.device_ser.write(pDev_cmd)
        LOGGER_INFO("To %s:    %s"%(self.device_type,pDev_cmd))
        time.sleep(0.4) 
        data = self.device_ser.read(self.device_ser.inWaiting())
        if not data:
            raise Exception("No return from device of command %s"%pDev_cmd)
        if not "<OK>" in data:
            raise Exception("No return from device of command %s"%pDev_cmd)
        LOGGER_INFO("From %s:     %s"%(self.device_type,data))

      
        #pc <-> testbed
        self.testbed_ser.write(pTb_cmd)
        LOGGER_INFO("To testbed:    %s"%pTb_cmd)
        time.sleep(0.4) 
        data = self.testbed_ser.read(self.testbed_ser.inWaiting())
        if not data:
            raise Exception("No return from testbed of command %s"%pTb_cmd)
        LOGGER_INFO("From testbed:     %s"%data)

        return data

    def _resultCompare(self, pDevType,pResult1, pResult2):
        result = []
        if pDevType == "switch":
            result_pos = self.switch_check_pos
        if pDevType == "remoter":
            result_pos = self.remoter_check_pos
        if pDevType == "sensor":
            result_pos = self.sensor_check_pos
        if pDevType == "other":
            strLength = len(pResult1)
            result_pos = range(strLength)
        for index in result_pos:
            if (pResult1[index] == pResult2[index]) and (pResult1[index] != "FAILED"):
                #if pResult1[index] != "FAILED":
                    result.append("PASSED")
            else:
                result.append("FAILED")
        return result

    def _closeSerialPort(self):
        self.device_ser.close()
        self.testbed_ser.close()


    def _startRfTest(self, pDev_cmd):
        
        resp = False
        data = ""
        self.device_ser.write(pDev_cmd)
        LOGGER_INFO("RF sent:   %s"%pDev_cmd)
        self.msgOut.emit("RF sent:  %s"%pDev_cmd)
        for i in range(self.timeout):
            self.msgOut.emit(u"Waiting %ss for return"%i)
            data = self.device_ser.read(self.device_ser.inWaiting())
            LOGGER_INFO("RF Received:     %s"%data)
            if not "<OK>" in data:
                time.sleep(1)
            else:
                resp = True
                break
        
        if resp == False:
            LOGGER_INFO("No return from device of command %s"%pDev_cmd)
        return resp

    def _sendUserKey(self, pDev_cmd):
        self.device_ser.write(pDev_cmd)
        LOGGER_INFO("RF sent:   user key ***** sent")
        self.msgOut.emit("RF sent:  user key ***** sent")
        time.sleep(0.4) 
        data = self.device_ser.read(self.device_ser.inWaiting())
        if not data:
            raise Exception("No return from device of command %s"%pDev_cmd)
        if not "<OK>" in data:
            raise Exception("No return from device of command %s"%pDev_cmd)
        LOGGER_INFO("RF Received:     %s"%data)

        return True



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1024, 703)
        self.line_setting_top = QtGui.QFrame(Form)
        self.line_setting_top.setGeometry(QtCore.QRect(120, 40, 271, 20))
        self.line_setting_top.setFrameShape(QtGui.QFrame.HLine)
        self.line_setting_top.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_setting_top.setObjectName(_fromUtf8("line_setting_top"))
        self.line_setting_buttom = QtGui.QFrame(Form)
        self.line_setting_buttom.setGeometry(QtCore.QRect(50, 320, 341, 16))
        self.line_setting_buttom.setFrameShape(QtGui.QFrame.HLine)
        self.line_setting_buttom.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_setting_buttom.setObjectName(_fromUtf8("line_setting_buttom"))
        self.line_setting_left = QtGui.QFrame(Form)
        self.line_setting_left.setGeometry(QtCore.QRect(40, 50, 20, 281))
        self.line_setting_left.setFrameShape(QtGui.QFrame.VLine)
        self.line_setting_left.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_setting_left.setObjectName(_fromUtf8("line_setting_left"))
        self.line_rf_left = QtGui.QFrame(Form)
        self.line_rf_left.setGeometry(QtCore.QRect(40, 360, 20, 81))
        self.line_rf_left.setFrameShape(QtGui.QFrame.VLine)
        self.line_rf_left.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_rf_left.setObjectName(_fromUtf8("line_rf_left"))
        self.Setting = QtGui.QLabel(Form)
        self.Setting.setGeometry(QtCore.QRect(60, 30, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Setting.setFont(font)
        self.Setting.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Setting.setAutoFillBackground(True)
        self.Setting.setStyleSheet(_fromUtf8("font: 75 16pt  \"MS Shell Dlg 2\";"))
        self.Setting.setAlignment(QtCore.Qt.AlignCenter)
        self.Setting.setWordWrap(False)
        self.Setting.setObjectName(_fromUtf8("Setting"))
        self.line_setting_right = QtGui.QFrame(Form)
        self.line_setting_right.setGeometry(QtCore.QRect(370, 50, 41, 281))
        self.line_setting_right.setFrameShape(QtGui.QFrame.VLine)
        self.line_setting_right.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_setting_right.setObjectName(_fromUtf8("line_setting_right"))
        self.pushButton_start = QtGui.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(270, 230, 91, 81))
        self.pushButton_start.setShortcut("Ctrl+S")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))

        self.line_rf_right = QtGui.QFrame(Form)
        self.line_rf_right.setGeometry(QtCore.QRect(380, 360, 21, 81))
        self.line_rf_right.setFrameShape(QtGui.QFrame.VLine)
        self.line_rf_right.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_rf_right.setObjectName(_fromUtf8("line_rf_right"))
        self.line_rf_top = QtGui.QFrame(Form)
        self.line_rf_top.setGeometry(QtCore.QRect(50, 350, 341, 20))
        self.line_rf_top.setFrameShape(QtGui.QFrame.HLine)
        self.line_rf_top.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_rf_top.setObjectName(_fromUtf8("line_rf_top"))
        self.line_rf_buttom = QtGui.QFrame(Form)
        self.line_rf_buttom.setGeometry(QtCore.QRect(50, 430, 341, 20))
        self.line_rf_buttom.setFrameShape(QtGui.QFrame.HLine)
        self.line_rf_buttom.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_rf_buttom.setObjectName(_fromUtf8("line_rf_buttom"))
        self.label_rf = QtGui.QLabel(Form)
        self.label_rf.setGeometry(QtCore.QRect(70, 380, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_rf.setFont(font)
        self.label_rf.setStyleSheet(_fromUtf8("font: 18pt \"Segoe UI\";\n"
""))
        self.label_rf.setObjectName(_fromUtf8("label_rf"))
        self.label_rf_result = QtGui.QLabel(Form)
        self.label_rf_result.setGeometry(QtCore.QRect(220, 380, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_rf_result.setFont(font)
        self.label_rf_result.setStyleSheet(_fromUtf8("font: 18pt \"Segoe UI\";\n"
""))
        self.label_rf_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_rf_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rf_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rf_result.setWordWrap(True)
        self.label_rf_result.setObjectName(_fromUtf8("label_rf_result"))
        self.label_debug = QtGui.QLabel(Form)
        self.label_debug.setGeometry(QtCore.QRect(50, 470, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_debug.setFont(font)
        self.label_debug.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_debug.setAutoFillBackground(True)
        self.label_debug.setStyleSheet(_fromUtf8("font: 75 16pt  \"MS Shell Dlg 2\";"))
        self.label_debug.setAlignment(QtCore.Qt.AlignCenter)
        self.label_debug.setWordWrap(False)
        self.label_debug.setObjectName(_fromUtf8("label_debug"))
        self.textBrowser_debug = QtGui.QTextBrowser(Form)
        self.textBrowser_debug.setGeometry(QtCore.QRect(50, 510, 341, 151))
        self.textBrowser_debug.setObjectName(_fromUtf8("textBrowser_debug"))
        self.line_switch_left = QtGui.QFrame(Form)
        self.line_switch_left.setGeometry(QtCore.QRect(410, 30, 20, 651))
        self.line_switch_left.setFrameShape(QtGui.QFrame.VLine)
        self.line_switch_left.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_switch_left.setObjectName(_fromUtf8("line_switch_left"))
        self.label_switch = QtGui.QLabel(Form)
        self.label_switch.setGeometry(QtCore.QRect(420, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_switch.setFont(font)
        self.label_switch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_switch.setAutoFillBackground(True)
        self.label_switch.setStyleSheet(_fromUtf8("font: 75 12pt  \"MS Shell Dlg 2\";"))
        self.label_switch.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch.setWordWrap(False)
        self.label_switch.setObjectName(_fromUtf8("label_switch"))
        self.line_switch_top = QtGui.QFrame(Form)
        self.line_switch_top.setGeometry(QtCore.QRect(520, 20, 161, 20))
        self.line_switch_top.setFrameShape(QtGui.QFrame.HLine)
        self.line_switch_top.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_switch_top.setObjectName(_fromUtf8("line_switch_top"))
        self.line_switch_right = QtGui.QFrame(Form)
        self.line_switch_right.setGeometry(QtCore.QRect(670, 30, 20, 651))
        self.line_switch_right.setFrameShape(QtGui.QFrame.VLine)
        self.line_switch_right.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_switch_right.setObjectName(_fromUtf8("line_switch_right"))
        self.line_switch_buttom = QtGui.QFrame(Form)
        self.line_switch_buttom.setGeometry(QtCore.QRect(420, 670, 261, 20))
        self.line_switch_buttom.setFrameShape(QtGui.QFrame.HLine)
        self.line_switch_buttom.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_switch_buttom.setObjectName(_fromUtf8("line_switch_buttom"))
        self.line_remoter_left = QtGui.QFrame(Form)
        self.line_remoter_left.setGeometry(QtCore.QRect(710, 30, 20, 391))
        self.line_remoter_left.setFrameShape(QtGui.QFrame.VLine)
        self.line_remoter_left.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_remoter_left.setObjectName(_fromUtf8("line_remoter_left"))
        self.label_remoter = QtGui.QLabel(Form)
        self.label_remoter.setGeometry(QtCore.QRect(720, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_remoter.setFont(font)
        self.label_remoter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_remoter.setAutoFillBackground(True)
        self.label_remoter.setStyleSheet(_fromUtf8("font: 75 12pt  \"MS Shell Dlg 2\";"))
        self.label_remoter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_remoter.setWordWrap(False)
        self.label_remoter.setObjectName(_fromUtf8("label_remoter"))
        self.line_remoter_top = QtGui.QFrame(Form)
        self.line_remoter_top.setGeometry(QtCore.QRect(790, 20, 191, 16))
        self.line_remoter_top.setFrameShape(QtGui.QFrame.HLine)
        self.line_remoter_top.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_remoter_top.setObjectName(_fromUtf8("line_remoter_top"))
        self.line_remoter_right = QtGui.QFrame(Form)
        self.line_remoter_right.setGeometry(QtCore.QRect(970, 30, 20, 391))
        self.line_remoter_right.setFrameShape(QtGui.QFrame.VLine)
        self.line_remoter_right.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_remoter_right.setObjectName(_fromUtf8("line_remoter_right"))
        self.line_remoter_buttom = QtGui.QFrame(Form)
        self.line_remoter_buttom.setGeometry(QtCore.QRect(720, 410, 261, 16))
        self.line_remoter_buttom.setFrameShape(QtGui.QFrame.HLine)
        self.line_remoter_buttom.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_remoter_buttom.setObjectName(_fromUtf8("line_remoter_buttom"))
        self.line_sensor_buttom = QtGui.QFrame(Form)
        self.line_sensor_buttom.setGeometry(QtCore.QRect(720, 670, 261, 16))
        self.line_sensor_buttom.setFrameShape(QtGui.QFrame.HLine)
        self.line_sensor_buttom.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_sensor_buttom.setObjectName(_fromUtf8("line_sensor_buttom"))
        self.line_sensor_top = QtGui.QFrame(Form)
        self.line_sensor_top.setGeometry(QtCore.QRect(790, 440, 191, 16))
        self.line_sensor_top.setFrameShape(QtGui.QFrame.HLine)
        self.line_sensor_top.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_sensor_top.setObjectName(_fromUtf8("line_sensor_top"))
        self.line_sensor_right = QtGui.QFrame(Form)
        self.line_sensor_right.setGeometry(QtCore.QRect(970, 450, 20, 231))
        self.line_sensor_right.setFrameShape(QtGui.QFrame.VLine)
        self.line_sensor_right.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_sensor_right.setObjectName(_fromUtf8("line_sensor_right"))
        self.layoutWidget_29 = QtGui.QWidget(Form)
        self.layoutWidget_29.setGeometry(QtCore.QRect(740, 470, 221, 191))
        self.layoutWidget_29.setObjectName(_fromUtf8("layoutWidget_29"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_29)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_52 = QtGui.QHBoxLayout()
        self.horizontalLayout_52.setObjectName(_fromUtf8("horizontalLayout_52"))
        self.label_sensor1 = QtGui.QLabel(self.layoutWidget_29)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_sensor1.setFont(font)
        self.label_sensor1.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_sensor1.setObjectName(_fromUtf8("label_sensor1"))
        self.horizontalLayout_52.addWidget(self.label_sensor1)
        self.label_sensor1_result = QtGui.QLabel(self.layoutWidget_29)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_sensor1_result.setFont(font)
        self.label_sensor1_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_sensor1_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_sensor1_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sensor1_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sensor1_result.setWordWrap(True)
        self.label_sensor1_result.setObjectName(_fromUtf8("label_sensor1_result"))
        self.horizontalLayout_52.addWidget(self.label_sensor1_result)
        self.verticalLayout_4.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_53 = QtGui.QHBoxLayout()
        self.horizontalLayout_53.setObjectName(_fromUtf8("horizontalLayout_53"))
        self.label_sensor2 = QtGui.QLabel(self.layoutWidget_29)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_sensor2.setFont(font)
        self.label_sensor2.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_sensor2.setObjectName(_fromUtf8("label_sensor2"))
        self.horizontalLayout_53.addWidget(self.label_sensor2)
        self.label_sensor2_result = QtGui.QLabel(self.layoutWidget_29)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_sensor2_result.setFont(font)
        self.label_sensor2_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_sensor2_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_sensor2_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sensor2_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sensor2_result.setWordWrap(True)
        self.label_sensor2_result.setObjectName(_fromUtf8("label_sensor2_result"))
        self.horizontalLayout_53.addWidget(self.label_sensor2_result)
        self.verticalLayout_4.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_54 = QtGui.QHBoxLayout()
        self.horizontalLayout_54.setObjectName(_fromUtf8("horizontalLayout_54"))
        self.label_sensor3 = QtGui.QLabel(self.layoutWidget_29)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_sensor3.setFont(font)
        self.label_sensor3.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_sensor3.setObjectName(_fromUtf8("label_sensor3"))
        self.horizontalLayout_54.addWidget(self.label_sensor3)
        self.label_sensor3_result = QtGui.QLabel(self.layoutWidget_29)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_sensor3_result.setFont(font)
        self.label_sensor3_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_sensor3_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_sensor3_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sensor3_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sensor3_result.setWordWrap(True)
        self.label_sensor3_result.setObjectName(_fromUtf8("label_sensor3_result"))
        self.horizontalLayout_54.addWidget(self.label_sensor3_result)
        self.verticalLayout_4.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_55 = QtGui.QHBoxLayout()
        self.horizontalLayout_55.setObjectName(_fromUtf8("horizontalLayout_55"))
        self.label_sensor4 = QtGui.QLabel(self.layoutWidget_29)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_sensor4.setFont(font)
        self.label_sensor4.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_sensor4.setObjectName(_fromUtf8("label_sensor4"))
        self.horizontalLayout_55.addWidget(self.label_sensor4)
        self.label_sensor4_result = QtGui.QLabel(self.layoutWidget_29)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_sensor4_result.setFont(font)
        self.label_sensor4_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_sensor4_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_sensor4_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sensor4_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sensor4_result.setWordWrap(True)
        self.label_sensor4_result.setObjectName(_fromUtf8("label_sensor4_result"))
        self.horizontalLayout_55.addWidget(self.label_sensor4_result)
        self.verticalLayout_4.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_62 = QtGui.QHBoxLayout()
        self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        self.label_sensor5 = QtGui.QLabel(self.layoutWidget_29)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_sensor5.setFont(font)
        self.label_sensor5.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_sensor5.setObjectName(_fromUtf8("label_sensor5"))
        self.horizontalLayout_62.addWidget(self.label_sensor5)
        self.label_sensor5_result = QtGui.QLabel(self.layoutWidget_29)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_sensor5_result.setFont(font)
        self.label_sensor5_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_sensor5_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_sensor5_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sensor5_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sensor5_result.setWordWrap(True)
        self.label_sensor5_result.setObjectName(_fromUtf8("label_sensor5_result"))
        self.horizontalLayout_62.addWidget(self.label_sensor5_result)
        self.verticalLayout_4.addLayout(self.horizontalLayout_62)
        self.label_sensor = QtGui.QLabel(Form)
        self.label_sensor.setGeometry(QtCore.QRect(720, 430, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_sensor.setFont(font)
        self.label_sensor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_sensor.setAutoFillBackground(True)
        self.label_sensor.setStyleSheet(_fromUtf8("font: 75 12pt  \"MS Shell Dlg 2\";"))
        self.label_sensor.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sensor.setWordWrap(False)
        self.label_sensor.setObjectName(_fromUtf8("label_sensor"))
        self.line_sensor_left = QtGui.QFrame(Form)
        self.line_sensor_left.setGeometry(QtCore.QRect(710, 450, 20, 231))
        self.line_sensor_left.setFrameShape(QtGui.QFrame.VLine)
        self.line_sensor_left.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_sensor_left.setObjectName(_fromUtf8("line_sensor_left"))
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(740, 50, 221, 361))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.label_remoter1 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter1.setFont(font)
        self.label_remoter1.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_remoter1.setObjectName(_fromUtf8("label_remoter1"))
        self.horizontalLayout_39.addWidget(self.label_remoter1)
        self.label_remoter1_result = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter1_result.setFont(font)
        self.label_remoter1_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_remoter1_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_remoter1_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_remoter1_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_remoter1_result.setWordWrap(True)
        self.label_remoter1_result.setObjectName(_fromUtf8("label_remoter1_result"))
        self.horizontalLayout_39.addWidget(self.label_remoter1_result)
        self.verticalLayout_3.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.label_remoter2 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter2.setFont(font)
        self.label_remoter2.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_remoter2.setObjectName(_fromUtf8("label_remoter2"))
        self.horizontalLayout_42.addWidget(self.label_remoter2)
        self.label_remoter2_result = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter2_result.setFont(font)
        self.label_remoter2_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_remoter2_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_remoter2_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_remoter2_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_remoter2_result.setWordWrap(True)
        self.label_remoter2_result.setObjectName(_fromUtf8("label_remoter2_result"))
        self.horizontalLayout_42.addWidget(self.label_remoter2_result)
        self.verticalLayout_3.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.label_remoter3 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter3.setFont(font)
        self.label_remoter3.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_remoter3.setObjectName(_fromUtf8("label_remoter3"))
        self.horizontalLayout_43.addWidget(self.label_remoter3)
        self.label_remoter3_result = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter3_result.setFont(font)
        self.label_remoter3_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_remoter3_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_remoter3_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_remoter3_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_remoter3_result.setWordWrap(True)
        self.label_remoter3_result.setObjectName(_fromUtf8("label_remoter3_result"))
        self.horizontalLayout_43.addWidget(self.label_remoter3_result)
        self.verticalLayout_3.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        self.label_remoter4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter4.setFont(font)
        self.label_remoter4.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_remoter4.setObjectName(_fromUtf8("label_remoter4"))
        self.horizontalLayout_44.addWidget(self.label_remoter4)
        self.label_remoter4_result = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter4_result.setFont(font)
        self.label_remoter4_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_remoter4_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_remoter4_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_remoter4_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_remoter4_result.setWordWrap(True)
        self.label_remoter4_result.setObjectName(_fromUtf8("label_remoter4_result"))
        self.horizontalLayout_44.addWidget(self.label_remoter4_result)
        self.verticalLayout_3.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        self.label_remoter5 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter5.setFont(font)
        self.label_remoter5.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_remoter5.setObjectName(_fromUtf8("label_remoter5"))
        self.horizontalLayout_45.addWidget(self.label_remoter5)
        self.label_remoter5_result = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter5_result.setFont(font)
        self.label_remoter5_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_remoter5_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_remoter5_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_remoter5_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_remoter5_result.setWordWrap(True)
        self.label_remoter5_result.setObjectName(_fromUtf8("label_remoter5_result"))
        self.horizontalLayout_45.addWidget(self.label_remoter5_result)
        self.verticalLayout_3.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtGui.QHBoxLayout()
        self.horizontalLayout_46.setObjectName(_fromUtf8("horizontalLayout_46"))
        self.label_remoter6 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter6.setFont(font)
        self.label_remoter6.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_remoter6.setObjectName(_fromUtf8("label_remoter6"))
        self.horizontalLayout_46.addWidget(self.label_remoter6)
        self.label_remoter6_result = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter6_result.setFont(font)
        self.label_remoter6_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_remoter6_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_remoter6_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_remoter6_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_remoter6_result.setWordWrap(True)
        self.label_remoter6_result.setObjectName(_fromUtf8("label_remoter6_result"))
        self.horizontalLayout_46.addWidget(self.label_remoter6_result)
        self.verticalLayout_3.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtGui.QHBoxLayout()
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        self.label_remoter7 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter7.setFont(font)
        self.label_remoter7.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_remoter7.setObjectName(_fromUtf8("label_remoter7"))
        self.horizontalLayout_47.addWidget(self.label_remoter7)
        self.label_remoter7_result = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter7_result.setFont(font)
        self.label_remoter7_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_remoter7_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_remoter7_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_remoter7_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_remoter7_result.setWordWrap(True)
        self.label_remoter7_result.setObjectName(_fromUtf8("label_remoter7_result"))
        self.horizontalLayout_47.addWidget(self.label_remoter7_result)
        self.verticalLayout_3.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_49 = QtGui.QHBoxLayout()
        self.horizontalLayout_49.setObjectName(_fromUtf8("horizontalLayout_49"))
        self.label_remoter8 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter8.setFont(font)
        self.label_remoter8.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_remoter8.setObjectName(_fromUtf8("label_remoter8"))
        self.horizontalLayout_49.addWidget(self.label_remoter8)
        self.label_remoter8_result = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter8_result.setFont(font)
        self.label_remoter8_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_remoter8_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_remoter8_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_remoter8_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_remoter8_result.setWordWrap(True)
        self.label_remoter8_result.setObjectName(_fromUtf8("label_remoter8_result"))
        self.horizontalLayout_49.addWidget(self.label_remoter8_result)
        self.verticalLayout_3.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_48 = QtGui.QHBoxLayout()
        self.horizontalLayout_48.setObjectName(_fromUtf8("horizontalLayout_48"))
        self.label_remoter9 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter9.setFont(font)
        self.label_remoter9.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_remoter9.setObjectName(_fromUtf8("label_remoter9"))
        self.horizontalLayout_48.addWidget(self.label_remoter9)
        self.label_remoter9_result = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_remoter9_result.setFont(font)
        self.label_remoter9_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_remoter9_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_remoter9_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_remoter9_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_remoter9_result.setWordWrap(True)
        self.label_remoter9_result.setObjectName(_fromUtf8("label_remoter9_result"))
        self.horizontalLayout_48.addWidget(self.label_remoter9_result)
        self.verticalLayout_3.addLayout(self.horizontalLayout_48)
        self.widget1 = QtGui.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(440, 50, 231, 621))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_swich1 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_swich1.setFont(font)
        self.label_swich1.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_swich1.setObjectName(_fromUtf8("label_swich1"))
        self.horizontalLayout_4.addWidget(self.label_swich1)
        self.label_switch1_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch1_result.setFont(font)
        self.label_switch1_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch1_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch1_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch1_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch1_result.setWordWrap(True)
        self.label_switch1_result.setObjectName(_fromUtf8("label_switch1_result"))
        self.horizontalLayout_4.addWidget(self.label_switch1_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_switch2 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch2.setFont(font)
        self.label_switch2.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch2.setObjectName(_fromUtf8("label_switch2"))
        self.horizontalLayout_22.addWidget(self.label_switch2)
        self.label_switch2_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch2_result.setFont(font)
        self.label_switch2_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch2_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch2_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch2_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch2_result.setWordWrap(True)
        self.label_switch2_result.setObjectName(_fromUtf8("label_switch2_result"))
        self.horizontalLayout_22.addWidget(self.label_switch2_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_switch3 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch3.setFont(font)
        self.label_switch3.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch3.setObjectName(_fromUtf8("label_switch3"))
        self.horizontalLayout_23.addWidget(self.label_switch3)
        self.label_switch3_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch3_result.setFont(font)
        self.label_switch3_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
"")) 
        self.label_switch3_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch3_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch3_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch3_result.setWordWrap(True)
        self.label_switch3_result.setObjectName(_fromUtf8("label_switch3_result"))
        self.horizontalLayout_23.addWidget(self.label_switch3_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_switch4 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch4.setFont(font)
        self.label_switch4.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch4.setObjectName(_fromUtf8("label_switch4"))
        self.horizontalLayout_24.addWidget(self.label_switch4)
        self.label_switch4_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch4_result.setFont(font)
        self.label_switch4_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch4_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch4_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch4_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch4_result.setWordWrap(True)
        self.label_switch4_result.setObjectName(_fromUtf8("label_switch4_result"))
        self.horizontalLayout_24.addWidget(self.label_switch4_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_switch5 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch5.setFont(font)
        self.label_switch5.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch5.setObjectName(_fromUtf8("label_switch5"))
        self.horizontalLayout_25.addWidget(self.label_switch5)
        self.label_switch5_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch5_result.setFont(font)
        self.label_switch5_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch5_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch5_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch5_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch5_result.setWordWrap(True)
        self.label_switch5_result.setObjectName(_fromUtf8("label_switch5_result"))
        self.horizontalLayout_25.addWidget(self.label_switch5_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_switch6 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch6.setFont(font)
        self.label_switch6.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch6.setObjectName(_fromUtf8("label_switch6"))
        self.horizontalLayout_26.addWidget(self.label_switch6)
        self.label_switch6_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch6_result.setFont(font)
        self.label_switch6_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch6_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch6_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch6_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch6_result.setWordWrap(True)
        self.label_switch6_result.setObjectName(_fromUtf8("label_switch6_result"))
        self.horizontalLayout_26.addWidget(self.label_switch6_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_switch7 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch7.setFont(font)
        self.label_switch7.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch7.setObjectName(_fromUtf8("label_switch7"))
        self.horizontalLayout_27.addWidget(self.label_switch7)
        self.label_switch7_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch7_result.setFont(font)
        self.label_switch7_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch7_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch7_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch7_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch7_result.setWordWrap(True)
        self.label_switch7_result.setObjectName(_fromUtf8("label_switch7_result"))
        self.horizontalLayout_27.addWidget(self.label_switch7_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_switch8 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch8.setFont(font)
        self.label_switch8.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch8.setObjectName(_fromUtf8("label_switch8"))
        self.horizontalLayout_28.addWidget(self.label_switch8)
        self.label_switch8_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch8_result.setFont(font)
        self.label_switch8_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch8_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch8_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch8_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch8_result.setWordWrap(True)
        self.label_switch8_result.setObjectName(_fromUtf8("label_switch8_result"))
        self.horizontalLayout_28.addWidget(self.label_switch8_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_switch9 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch9.setFont(font)
        self.label_switch9.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch9.setObjectName(_fromUtf8("label_switch9"))
        self.horizontalLayout_29.addWidget(self.label_switch9)
        self.label_switch9_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch9_result.setFont(font)
        self.label_switch9_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch9_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch9_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch9_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch9_result.setWordWrap(True)
        self.label_switch9_result.setObjectName(_fromUtf8("label_switch9_result"))
        self.horizontalLayout_29.addWidget(self.label_switch9_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_switch10 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch10.setFont(font)
        self.label_switch10.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch10.setObjectName(_fromUtf8("label_switch10"))
        self.horizontalLayout_30.addWidget(self.label_switch10)
        self.label_switch10_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch10_result.setFont(font)
        self.label_switch10_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch10_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch10_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch10_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch10_result.setWordWrap(True)
        self.label_switch10_result.setObjectName(_fromUtf8("label_switch10_result"))
        self.horizontalLayout_30.addWidget(self.label_switch10_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_switch11 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch11.setFont(font)
        self.label_switch11.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch11.setObjectName(_fromUtf8("label_switch11"))
        self.horizontalLayout_31.addWidget(self.label_switch11)
        self.label_switch11_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch11_result.setFont(font)
        self.label_switch11_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch11_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch11_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch11_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch11_result.setWordWrap(True)
        self.label_switch11_result.setObjectName(_fromUtf8("label_switch11_result"))
        self.horizontalLayout_31.addWidget(self.label_switch11_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_switch12 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch12.setFont(font)
        self.label_switch12.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch12.setObjectName(_fromUtf8("label_switch12"))
        self.horizontalLayout_32.addWidget(self.label_switch12)
        self.label_switch12_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch12_result.setFont(font)
        self.label_switch12_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch12_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch12_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch12_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch12_result.setWordWrap(True)
        self.label_switch12_result.setObjectName(_fromUtf8("label_switch12_result"))
        self.horizontalLayout_32.addWidget(self.label_switch12_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_switch13 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch13.setFont(font)
        self.label_switch13.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch13.setObjectName(_fromUtf8("label_switch13"))
        self.horizontalLayout_33.addWidget(self.label_switch13)
        self.label_switch13_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch13_result.setFont(font)
        self.label_switch13_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch13_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch13_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch13_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch13_result.setWordWrap(True)
        self.label_switch13_result.setObjectName(_fromUtf8("label_switch13_result"))
        self.horizontalLayout_33.addWidget(self.label_switch13_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_switch14 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch14.setFont(font)
        self.label_switch14.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch14.setObjectName(_fromUtf8("label_switch14"))
        self.horizontalLayout_34.addWidget(self.label_switch14)
        self.label_switch14_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch14_result.setFont(font)
        self.label_switch14_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch14_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch14_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch14_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch14_result.setWordWrap(True)
        self.label_switch14_result.setObjectName(_fromUtf8("label_switch14_result"))
        self.horizontalLayout_34.addWidget(self.label_switch14_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_switch15 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch15.setFont(font)
        self.label_switch15.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch15.setObjectName(_fromUtf8("label_switch15"))
        self.horizontalLayout_35.addWidget(self.label_switch15)
        self.label_switch15_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch15_result.setFont(font)
        self.label_switch15_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch15_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch15_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch15_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch15_result.setWordWrap(True)
        self.label_switch15_result.setObjectName(_fromUtf8("label_switch15_result"))
        self.horizontalLayout_35.addWidget(self.label_switch15_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.label_switch16 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch16.setFont(font)
        self.label_switch16.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch16.setObjectName(_fromUtf8("label_switch16"))
        self.horizontalLayout_36.addWidget(self.label_switch16)
        self.label_switch16_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch16_result.setFont(font)
        self.label_switch16_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch16_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch16_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch16_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch16_result.setWordWrap(True)
        self.label_switch16_result.setObjectName(_fromUtf8("label_switch16_result"))
        self.horizontalLayout_36.addWidget(self.label_switch16_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_switch17 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch17.setFont(font)
        self.label_switch17.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch17.setObjectName(_fromUtf8("label_switch17"))
        self.horizontalLayout_37.addWidget(self.label_switch17)
        self.label_switch17_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch17_result.setFont(font)
        self.label_switch17_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch17_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch17_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch17_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch17_result.setWordWrap(True)
        self.label_switch17_result.setObjectName(_fromUtf8("label_switch17_result"))
        self.horizontalLayout_37.addWidget(self.label_switch17_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_switch18 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch18.setFont(font)
        self.label_switch18.setStyleSheet(_fromUtf8("font: 9pt \"MS Shell Dlg 2\";"))
        self.label_switch18.setObjectName(_fromUtf8("label_switch18"))
        self.horizontalLayout_38.addWidget(self.label_switch18)
        self.label_switch18_result = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_switch18_result.setFont(font)
        self.label_switch18_result.setStyleSheet(_fromUtf8("font: 9pt \"Segoe UI\";\n"
""))
        self.label_switch18_result.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_switch18_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_switch18_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_switch18_result.setWordWrap(True)
        self.label_switch18_result.setObjectName(_fromUtf8("label_switch18_result"))
        self.horizontalLayout_38.addWidget(self.label_switch18_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_38)
        self.widget2 = QtGui.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(80, 80, 261, 131))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_device_name = QtGui.QLabel(self.widget2)
        self.label_device_name.setStyleSheet(_fromUtf8("font: 12pt \"MS Shell Dlg 2\";"))
        self.label_device_name.setObjectName(_fromUtf8("label_device_name"))
        self.horizontalLayout.addWidget(self.label_device_name)
        self.comboBox_device_name = QtGui.QComboBox(self.widget2)
        self.comboBox_device_name.setObjectName(_fromUtf8("comboBox_device_name"))
        self.horizontalLayout.addWidget(self.comboBox_device_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_device_port = QtGui.QLabel(self.widget2)
        self.label_device_port.setStyleSheet(_fromUtf8("font: 12pt \"MS Shell Dlg 2\";"))
        self.label_device_port.setObjectName(_fromUtf8("label_device_port"))
        self.horizontalLayout_2.addWidget(self.label_device_port)
        self.comboBox_device_port = QtGui.QComboBox(self.widget2)
        self.comboBox_device_port.setObjectName(_fromUtf8("comboBox_device_port"))
        self.horizontalLayout_2.addWidget(self.comboBox_device_port)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_testbed_port = QtGui.QLabel(self.widget2)
        self.label_testbed_port.setStyleSheet(_fromUtf8("font: 12pt \"MS Shell Dlg 2\";"))
        self.label_testbed_port.setObjectName(_fromUtf8("label_testbed_port"))
        self.horizontalLayout_3.addWidget(self.label_testbed_port)
        self.comboBox_testbed_port = QtGui.QComboBox(self.widget2)
        self.comboBox_testbed_port.setObjectName(_fromUtf8("comboBox_testbed_port"))
        self.horizontalLayout_3.addWidget(self.comboBox_testbed_port)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_setting_top.raise_()
        self.line_setting_buttom.raise_()
        self.line_setting_left.raise_()
        self.line_rf_left.raise_()
        self.Setting.raise_()
        self.line_setting_right.raise_()
        self.label_device_name.raise_()
        self.label_testbed_port.raise_()
        self.label_device_port.raise_()
        self.comboBox_device_name.raise_()
        self.comboBox_device_port.raise_()
        self.comboBox_testbed_port.raise_()
        self.pushButton_start.raise_()
        self.line_rf_right.raise_()
        self.line_rf_top.raise_()
        self.line_rf_buttom.raise_()
        self.label_rf.raise_()
        self.label_rf_result.raise_()
        self.label_debug.raise_()
        self.textBrowser_debug.raise_()
        self.line_switch_left.raise_()
        self.label_switch.raise_()
        self.line_switch_top.raise_()
        self.label_swich1.raise_()
        self.label_switch1_result.raise_()
        self.line_switch_right.raise_()
        self.line_switch_buttom.raise_()
        self.line_remoter_left.raise_()
        self.label_remoter.raise_()
        self.line_remoter_top.raise_()
        self.line_remoter_right.raise_()
        self.line_remoter_buttom.raise_()
        self.line_sensor_buttom.raise_()
        self.line_sensor_top.raise_()
        self.line_sensor_right.raise_()
        self.layoutWidget_29.raise_()
        self.label_sensor.raise_()
        self.line_sensor_left.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        

        self.pushButton_start.clicked.connect(self.startTest)
        self.portList = self._getPortList()

        self.comboBox_device_name.addItems([u'墙壁开关',u'传感器',u'遥控器'])
        self.comboBox_device_port.addItems(self.portList)
        self.comboBox_testbed_port.addItems(self.portList)



        self.switch_upList = [self.label_switch1_result, self.label_switch2_result, self.label_switch3_result, self.label_switch4_result, self.label_switch5_result, \
                        self.label_switch6_result, self.label_switch7_result, self.label_switch8_result, self.label_switch9_result, self.label_switch10_result, \
                        self.label_switch11_result, self.label_switch12_result, self.label_switch13_result, self.label_switch14_result, \
                        self.label_switch15_result,self.label_switch16_result,self.label_switch17_result,self.label_switch18_result]
        self.remoter_upList = [self.label_remoter1_result,self.label_remoter2_result, self.label_remoter3_result, self.label_remoter4_result, self.label_remoter5_result,\
                        self.label_remoter6_result,self.label_remoter7_result, self.label_remoter8_result, self.label_remoter9_result]
        self.sensor_upList = [self.label_sensor1_result,self.label_sensor2_result, self.label_sensor3_result, self.label_sensor4_result, self.label_sensor5_result]





    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Testbench", None))
        self.Setting.setText(_translate("Form", "设置", None))
        self.pushButton_start.setText(_translate("Form", "开始(S)", None))
        self.label_rf.setText(_translate("Form", "传输测试", None))
        self.label_rf_result.setText(_translate("Form", "N/A", None))
        self.label_debug.setText(_translate("Form", "Debug", None))
        self.label_switch.setText(_translate("Form", "墙面开关", None))
        self.label_remoter.setText(_translate("Form", "遥控器", None))
        self.label_sensor1.setText(_translate("Form", "KEY(TP14)", None))
        self.label_sensor1_result.setText(_translate("Form", "N/A", None))
        self.label_sensor2.setText(_translate("Form", "DT_EN(TP13)", None))
        self.label_sensor2_result.setText(_translate("Form", "N/A", None))
        self.label_sensor3.setText(_translate("Form", "LS_EN(TP12)", None))
        self.label_sensor3_result.setText(_translate("Form", "N/A", None))
        self.label_sensor4.setText(_translate("Form", "LED_G(TP18)", None))
        self.label_sensor4_result.setText(_translate("Form", "N/A", None))
        self.label_sensor5.setText(_translate("Form", "LED_R(TP17)", None))
        self.label_sensor5_result.setText(_translate("Form", "N/A", None))
        self.label_sensor.setText(_translate("Form", "传感器", None))
        self.label_remoter1.setText(_translate("Form", "KEY0(TP2)", None))
        self.label_remoter1_result.setText(_translate("Form", "N/A", None))
        self.label_remoter2.setText(_translate("Form", "BrdID0(P34)", None))
        self.label_remoter2_result.setText(_translate("Form", "N/A", None))
        self.label_remoter3.setText(_translate("Form", "BrdChk(TP17)", None))
        self.label_remoter3_result.setText(_translate("Form", "N/A", None))
        self.label_remoter4.setText(_translate("Form", "LED_R(TP6)", None))
        self.label_remoter4_result.setText(_translate("Form", "N/A", None))
        self.label_remoter5.setText(_translate("Form", "LED_G(TP5)", None))
        self.label_remoter5_result.setText(_translate("Form", "N/A", None))
        self.label_remoter6.setText(_translate("Form", "Beeper(TP9)", None))
        self.label_remoter6_result.setText(_translate("Form", "N/A", None))
        self.label_remoter7.setText(_translate("Form", "KEY3(TP3)", None))
        self.label_remoter7_result.setText(_translate("Form", "N/A", None))
        self.label_remoter8.setText(_translate("Form", "KEY2(TP1)", None))
        self.label_remoter8_result.setText(_translate("Form", "N/A", None))
        self.label_remoter9.setText(_translate("Form", "KEY1(TP4)", None))
        self.label_remoter9_result.setText(_translate("Form", "N/A", None))
        self.label_swich1.setText(_translate("Form", "Key0(TP22)", None))
        self.label_switch1_result.setText(_translate("Form", "N/A", None))
        self.label_switch2.setText(_translate("Form", "BrdID0(TP9)", None))
        self.label_switch2_result.setText(_translate("Form", "N/A", None))
        self.label_switch3.setText(_translate("Form", "BrdChk(TP26)", None))
        self.label_switch3_result.setText(_translate("Form", "N/A", None))
        self.label_switch4.setText(_translate("Form", "K3LED(TP14)", None))
        self.label_switch4_result.setText(_translate("Form", "N/A", None))
        self.label_switch5.setText(_translate("Form", "K2LED(TP15)", None))
        self.label_switch5_result.setText(_translate("Form", "N/A", None))
        self.label_switch6.setText(_translate("Form", "K1LED(TP16)", None))
        self.label_switch6_result.setText(_translate("Form", "N/A", None))
        self.label_switch7.setText(_translate("Form", "A1(TP5)", None))
        self.label_switch7_result.setText(_translate("Form", "N/A", None))
        self.label_switch8.setText(_translate("Form", "A2(TP7)", None))
        self.label_switch8_result.setText(_translate("Form", "N/A", None))
        self.label_switch9.setText(_translate("Form", "A3(TP8)", None))
        self.label_switch9_result.setText(_translate("Form", "N/A", None))
        self.label_switch10.setText(_translate("Form", "LD1(TP11)", None))
        self.label_switch10_result.setText(_translate("Form", "N/A", None))
        self.label_switch11.setText(_translate("Form", "LD2(TP12)", None))
        self.label_switch11_result.setText(_translate("Form", "N/A", None))
        self.label_switch12.setText(_translate("Form", "LD3(TP13)", None))
        self.label_switch12_result.setText(_translate("Form", "N/A", None))
        self.label_switch13.setText(_translate("Form", "KEY3(TP23)", None))
        self.label_switch13_result.setText(_translate("Form", "N/A", None))
        self.label_switch14.setText(_translate("Form", "KEY2(TP24)", None))
        self.label_switch14_result.setText(_translate("Form", "N/A", None))
        self.label_switch15.setText(_translate("Form", "KEY1(TP25)", None))
        self.label_switch15_result.setText(_translate("Form", "N/A", None))
        self.label_switch16.setText(_translate("Form", "LED3(TP1)", None))
        self.label_switch16_result.setText(_translate("Form", "N/A", None))
        self.label_switch17.setText(_translate("Form", "LED1(TP3)", None))
        self.label_switch17_result.setText(_translate("Form", "N/A", None))
        self.label_switch18.setText(_translate("Form", "LED2(TP2)", None))
        self.label_switch18_result.setText(_translate("Form", "N/A", None))
        self.label_device_name.setText(_translate("Form", "设备名称", None))
        self.label_device_port.setText(_translate("Form", "设备串口", None))
        self.label_testbed_port.setText(_translate("Form", "测试板串口", None))


    def _getPortList(self):
        getPortList = list(serial.tools.list_ports.comports())
        tempPortList = []
        for item in getPortList:
            tempPortList.append(item[0])
        return tempPortList

    def startTest(self):
        self.thread = MyThread()
        tempDev = str(self.comboBox_device_name.currentText())  
        if tempDev == "墙壁开关":
            self.thread.setDevType('switch')
        if tempDev == "遥控器":
            self.thread.setDevType('remoter')
        if tempDev == "传感器":
            self.thread.setDevType('sensor')
        
        self.thread.setDevPort(self.comboBox_device_port.currentText())
        self.thread.setDevRate('9600')
        self.thread.setTbPort(self.comboBox_testbed_port.currentText())
        self.thread.setTbRate('115200')
        self.thread.sinOut.connect(self.updateResultData)
        self.thread.sinOutRF.connect(self.updateRFResultData)
        self.thread.msgOut.connect(self.updateBrowserData)
        self.thread.errorOut.connect(self.errorHandler)
        self.thread.start()
        self.buttonChange()
        
    #def startRfTest(self):       
       # self.thread2 = MyThread2()
        #self.thread2.setDevPort(self.device_port.currentText())
        #self.thread2.setDevRate(self.device_rate.currentText())
        #self.thread2.setTbPort(self.testbed_port.currentText())
        #self.thread2.setTbRate(self.testbed_rate.currentText())
        #self.thread2.msgOut.connect(self.updateBrowserData)
        #self.thread2.errorOut.connect(self.errorHandler)
        #self.thread2.sinOut.connect(self.updateRFResultData)
        #self.thread2.start()
        #self.buttonChange()


    def errorHandler(self,text):
        self.textBrowser_debug.append(text)
        self.textBrowser_debug.append(u"<font color='red'>测试意外终止，请重启软件.</font>")
        self.finish()

    def updateBrowserData(self, text):
        self.textBrowser_debug.append(text)

    def updateResultData(self,text):
        time.sleep(3)
        tempList = text.split(",")
        if tempList[0] == "switch":
            updateList = self.switch_upList
        if tempList[0] == "remoter":
            updateList = self.remoter_upList
        if tempList[0] == "sensor":
            updateList = self.sensor_upList
        idx = 1

        for item in updateList:
            if tempList[idx] == "PASSED":
                item.setText("<font color='green'>PASSED</font>")
            else:
                item.setText("<font color='red'>FAILED</font>")
            idx = idx + 1
        

    def updateRFResultData(self,text):
        if text == "PASSED":
            self.label_rf_result.setText("<font color='green'>PASSED</font>")
        else:
            self.label_rf_result.setText("<font color='red'>FAILED</font>")
        self.finish()

    def finish(self):
        self.pushButton_start.setEnabled(True)


    def buttonChange(self):
        for item in [self.switch_upList, self.remoter_upList, self.sensor_upList]:
            map(lambda s: s.setText("N/A"), item)
        self.label_rf_result.setText("N/A")
        self.pushButton_start.setEnabled(False)



if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())